//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Courses.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class T_Students
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string StudentFamily { get; set; }
        public Nullable<int> StudentAge { get; set; }
        public string StudentPhoneNumber { get; set; }
        public string StudentPassword { get; set; }
        public string StudentEmail { get; set; }
        public bool StudentGender { get; set; }
        public Nullable<bool> StudentMarital { get; set; }
        public string StudentImageName { get; set; }
        public System.DateTime StudentRegisterDate { get; set; }
        public bool StudentIsActive { get; set; }
    }
}
